### ISSUE TITLE
Documentation should mention health check port

### ISSUE THREAD

**Issue by ecker00** [peytonyip/docker-nginx-brotli#47]
I noticed that in recent update, it's been added a `HEALTHCHECK` on port 80. Documentation should probably mention to change this port if a custom port is used.

I see this new layer:
```
HEALTHCHECK &{["CMD-SHELL" "nc -z localhost 80 || exit 1"] "10s" "5s" "1m0s" "0s" '\x00'}
```

Myself I'm using this to override it to port 8080:
```
HEALTHCHECK --interval=10s --timeout=5s --retries=3 \
  CMD nc -z localhost 8080 || exit 1
```

Without it I had my images roll back, as they didn't report as healthy.

**Comment by peytonyip** [comment]
Thanks for your advice

**Comment by ecker00** [comment]
Perfect, was stuck on this for a while, good to have it documented for everyone. 👍
