### ISSUE TITLE
Current stable nginx version (1.22.1) separate tag 

### ISSUE THREAD

**Issue by Novemb3r** [peytonyip/docker-nginx-brotli#5]
Hello! Thank you for the great image.
We are using stable versions of nginx. Yesterday I tried to update our images to 1.22.1 (which is latest stable in https://nginx.org/en/download.html), but I noticed that 1.22.1 does not exist in docker hub.
There is 1.22.0 in stable tag, but maybe there should be separate tag for 1.22?

**Comment by peytonyip** [comment]
Thank you for your suggestion, it has been updated, you try it

**Comment by Novemb3r** [comment]
Thank you!
